# Obter a lista de animais
GET http://localhost:3000/animais
Content-Type: application/json
###

# Inserir novo animal
POST http://localhost:3000/animais
Content-Type: application/json 

{
 "tipo": "cachorro",
 "nome": "ozzi",
 "idade": 3
}
###

# Alterar um animal
PUT http://localhost:3000/animais
Content-Type: application/json

{
    "_id": "622bdfc532811febb4116060",
    "tipo": "cachorro",
    "nome": "ozzi",
    "idade": 4
}
###
# Excluir um animal pelo id
DELETE http://localhost:3000/animais/61155f6d8709e63275d0e71a
Content-Type: application/json

###

# Obter animal pelo id
GET http://localhost:3000/animais/61155fb98709e63275d0e71b
Content-Type: application/json

###

# Obter animais filtrando
GET http://localhost:3000/animais/filtro/cachorro
Content-Type: application/json

###



