# Obter a lista de colaboradores
GET http://localhost:3000/colaborador
Content-Type: application/json
###

# Inserir novo colaborador
POST http://localhost:3000/colaborador
Content-Type: application/json

{
 
 "nome": "Joao",
 "idade": 21,
 "senha": "foguinho"
}
###

# Alterar um colaborador
PUT http://localhost:3000/colaborador
Content-Type: application/json

{
 "_id": "622bea6a8bab3763bb24124a",
 "nome": "Pedro",
 "idade": 22,
 "senha": "Fogo"
}
###


# Excluir um colaborador pelo id
DELETE http://localhost:3000/colaborador/622bea6a8bab3763bb24124a
Content-Type: application/json
###

# Obter colaborador pelo id
GET http://localhost:3000/colaborador/622be6d0b057bea289bae39f
Content-Type: application/json
###


# Obter colaboradores filtrando
GET http://localhost:3000/colaborador/filtro/ozzi
Content-Type: application/json
###